### ISSUE TITLE
MD-SAPT v1.1.0

### ISSUE THREAD

**Issue by ALescoulie** [calpolyccg/MDSAPT#21]
## MD-SAPT Improved Full Release

A checklist of the things I wan't to get done for the next release. This is what I want to have done when we announce the project. I'll also create individual issues for each step so they can done as PRs in the development branch before being merged into master.

- [ ] Make SAPT run multithreaded #15 
- [ ] Reuse wave functions in for repeated selection in a single frame #19 
- [ ] Save all SAPT energies #20 
- [ ] Fix and update documentation #18 

In addition I'd like to test the scripts to ensure they work as expected. If anyone else has suggestions add them.
